<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="Django default" uuid="1d7ab555-2882-479e-bfd7-51903b178163">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/../Alex_note/day20/day20/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:mysql://127.0.0.1:3306/testdb</jdbc-url>
      <explain-plan-config>
        <provider>com.intellij.database.plan.mysql.MysqlExplainPlanProvider</provider>
      </explain-plan-config>
    </data-source>
    <data-source source="LOCAL" name="Django default2" uuid="3f66b5e0-74d7-4f8b-98d9-279a8fc11ca7">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/../Alex_note/day20/day20/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:F:\Python\Alex_note\day20\db.sqlite3</jdbc-url>
    </data-source>
  </component>
</project>